java_library(
    name = "conf",
    srcs = glob(["*.java"]),
    visibility = ["//visibility:public"],
    deps = [
        "//compass/milestone",
        "//compass/sign:common",
        "//third-party/jota",
        "@com_beust_jcommander//jar",
        "@com_google_guava_guava//jar",
        "@junit_junit//jar",
    ],
)
